# Generated by Django 2.0.4 on 2018-04-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
